# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('true_false', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tf_question',
            options={'ordering': ['category'], 'verbose_name': 'Вопрос с ответом Да/Нет', 'verbose_name_plural': 'Вопросы с ответом Да/Нет'},
        ),
        migrations.AlterField(
            model_name='tf_question',
            name='correct',
            field=models.BooleanField(default=False, help_text="Отметьте, если ответ на вопрос 'Да'. Оставьте пустым, если ответ 'Нет'", verbose_name='Правильный ответ'),
        ),
    ]
