# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20171018_0845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['category', 'subcategory'], 'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
    ]
