# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20171024_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['code', 'category', 'subcategory'], 'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AddField(
            model_name='quiz',
            name='code',
            field=models.CharField(blank=True, max_length=4, verbose_name='Code'),
        ),
    ]
