# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='essay_question',
            options={'verbose_name': 'Эссе', 'verbose_name_plural': 'Эссе'},
        ),
    ]
