# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0002_auto_20171013_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Int_Question',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.Question')),
                ('correct', models.IntegerField(default=False, help_text='Answer must be an integer number', verbose_name='Верно')),
            ],
            options={
                'verbose_name': 'Integer Question',
                'verbose_name_plural': 'Integer Questions',
                'ordering': ['category'],
            },
            bases=('quiz.question',),
        ),
    ]
