# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('int_question', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='int_question',
            options={'ordering': ['category', 'sub_category'], 'verbose_name': 'Целочисленный вопрос', 'verbose_name_plural': 'Целочисленный вопрос'},
        ),
        migrations.AlterField(
            model_name='int_question',
            name='correct',
            field=models.IntegerField(default=False, help_text='Ответом должно быть целое число', verbose_name='Правильный ответ'),
        ),
    ]
