# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_magicnode_long_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magicnode',
            name='long_desc',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
