# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_auto_20171208_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='magicnode',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='magicnode',
            name='video',
            field=smartfields.fields.FileField(null=True, upload_to=''),
        ),
    ]
