# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multichoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='mcquestion',
            options={'verbose_name': 'Вопрос с несколькими вариантами ответов', 'verbose_name_plural': 'Вопросы с несколькими вариантами ответов'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.CharField(help_text='Введите текст ответа', max_length=1000, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=False, help_text='Это правильный ответ?', verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multichoice.MCQuestion', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='mcquestion',
            name='answer_order',
            field=models.CharField(blank=True, choices=[('content', 'Сообщение'), ('random', 'Случайно'), ('none', 'Нет')], help_text='Порядок отображения вопросов', max_length=30, null=True, verbose_name='Порядок вопросов'),
        ),
    ]
